---
- name: Convert LEMP into LAMP
  hosts: localhost
  become: yes

  vars:
    new_pkg: httpd
    web_pkg: nginx # hard-coded
    db_pkg: mariadb105-server
    php_pkg:
      - php
      - php-fpm
    web_service: nginx
    db_service: mariadb
    php_service: php-fpm
    new_pkg_service: httpd
    web_file_path: /var/www/html/index.php

  tasks:
    - name: Install httpd
      ansible.builtin.dnf:
        name: "{{ new_pkg }}"
        state: present

    - name: Install nginx
      ansible.builtin.dnf:
        name: "{{ web_pkg }}"
        state: present

    - name: Install mariadb
      ansible.builtin.dnf:
        name: "{{ db_pkg }}"
        state: present

    - name: Install PHP packages
      ansible.builtin.dnf:
        name: "{{ php_pkg }}"
        state: present

    - name: Start and enable httpd
      systemd_service:
        name: "{{ new_pkg_service }}"
        state: started
        enabled: true

    - name: Stop and disable nginx
      systemd_service:
        name: "{{ web_service }}"
        state: stopped
        enabled: false

    - name: Start and enable mariadb
      ansible.builtin.systemd_service:
        name: "{{ db_service }}"
        state: started
        enabled: true

    - name: Start and enable php-fpm
      ansible.builtin.systemd_service:
        name: "{{ php_service }}"
        state: started
        enabled: true

    - name: Deploy PHP page
      ansible.builtin.copy:
        dest: "{{ web_file_path }}"
        content: |
          <?php
          phpinfo();
          ?>
